/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2024-05-24 21:07:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class docente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1716582517468L));
    _jspx_dependants.put("jar:file:/C:/Users/Jhostin%20PC/Desktop/PROYECTO%20WEB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DWI-Semana09/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1697313970000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "intranet.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Mantenimiento Docente</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/@sweetalert2/theme-bulma/bulma.css\" rel=\"stylesheet\">\r\n");
      out.write("<style >\r\n");
      out.write(".modal-header{\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground: #428bca;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("  \t\tjustify-content: center;\r\n");
      out.write("  \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block {\r\n");
      out.write("\t  \t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control-label {\r\n");
      out.write("\t  color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control {\r\n");
      out.write("\t  border: 1px solid red;\r\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h1 class=\"mt-5 text-center\">Listado de Docentes</h1>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Button trigger modal -->\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" \r\n");
      out.write("\tdata-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Nuevo Docente</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Docente</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        \r\n");
      out.write("      <form id=\"formDocente\" method=\"post\" action=\"ServletDocente?accion=grabar\">\r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Código</label>\r\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" name=\"codigo\" id=\"id-codigo\" value=\"0\" readonly>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t    <label for=\"exampleInputEmail1\" class=\"form-label\">Nombre</label>\r\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" name=\"nombre\" id=\"id-nombre\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("  \r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t    <label for=\"exampleInputPassword1\" class=\"form-label\">Paterno</label>\r\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" name=\"paterno\" id=\"id-paterno\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("  \r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t    <label for=\"exampleInputPassword1\" class=\"form-label\">Materno</label>\r\n");
      out.write("\t\t    <input type=\"text\" class=\"form-control\" name=\"materno\" id=\"id-materno\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("  \r\n");
      out.write("\t    <div class=\"form-group\">\r\n");
      out.write("\t    <label for=\"exampleInputPassword1\" class=\"form-label\">Hijos</label>\r\n");
      out.write("\t    <input type=\"text\" class=\"form-control\" name=\"hijos\" id=\"id-hijos\">\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\" class=\"form-label\">Sueldo</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" name=\"sueldo\" id=\"id-sueldo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\" class=\"form-label\">Sexo</label>\r\n");
      out.write("    <select class=\"form-select\" name=\"sexo\" id=\"id-sexo\">\r\n");
      out.write("\t  <option value=\"\" selected>[Seleccionar sexo]</option>\r\n");
      out.write("\t  <option value=\"Masculino\">Masculino</option>\r\n");
      out.write("\t  <option value=\"Femenino\">Femenino</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("  </div>\r\n");
      out.write("  \t<div class=\"form-group\">\r\n");
      out.write("\t\t<label for=\"exampleInputPassword1\" class=\"form-label\">Colegio</label>\r\n");
      out.write("\t\t<select class=\"form-select\" name=\"colegio\" id=\"id-colegio\">\r\n");
      out.write("\t\t\t<option value=\" \">[Seleccione colegio]</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\t\t<div class=\"modal-footer\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-primary\">Grabar</button>\r\n");
      out.write("             <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\" id=\"btn-cerrar\">Cerrar</button>\r\n");
      out.write("      \t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>  \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"mt-3\">\r\n");
      out.write("  <table id=\"TableDocente\" class=\"table table-striped\" style=\"width:100%\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Código</th>\r\n");
      out.write("                <th>Nombres</th>\r\n");
      out.write("                <th>Paterno</th>\r\n");
      out.write("                <th>Materno</th>\r\n");
      out.write("                <th>Sexo</th>\r\n");
      out.write("                <th>Hijos</th>\r\n");
      out.write("                <th>Sueldo</th>\r\n");
      out.write("                <th></th>\r\n");
      out.write("                <th></th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          <!-- \r\n");
      out.write("        \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("             -->\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- libreria principal de JQUERY -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- libreria JS de bootstrap -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- libreria JS de la tabla -->\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- libreria para validar (bootstrap validator) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- validar si existe el atrubuto MENSAJE -->\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- eliminar atributo de tipo sesión MENSAJE -->\r\n");
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//invocar funciones de carga\r\n");
      out.write("\t\tcargarColegios();\r\n");
      out.write("\t\tcargarDocentes()\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//crear función para leer JSON\r\n");
      out.write("\t\tfunction cargarColegios(){\r\n");
      out.write("\t\t\t$.get(\"ServletColegioJSON\",function(response){\t\r\n");
      out.write("\t\t\t\t//bucle each \"for\"\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t//llenar combo\r\n");
      out.write("\t\t\t\t\t$(\"#id-colegio\").append(\"<option value='\"+item.codigo+\"'>\"+item.nombre+\"</option>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//crear función para leer JSON de docentes\r\n");
      out.write("\t\tfunction cargarDocentes(){\r\n");
      out.write("\t\t\t$.get(\"ServletDocenteJSON\",function(response){\t\r\n");
      out.write("\t\t\t\tlet botonEditar=\"<button type='button' class='btn btn-success btn-editar' data-bs-toggle='modal' data-bs-target='#exampleModal'>Editar</button>\";\r\n");
      out.write("                let botonEliminar=\"<button type='button' class='btn btn-danger btn-eliminar'>Eliminar</button>\";\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t//llenar tabla\r\n");
      out.write("\t\t\t\t\t$(\"#TableDocente\").append(\"<tr><td>\"+item.codigo+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t \"<td>\"+item.nombre+\"</td>\"+\"<td>\"+item.paterno+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t \"<td>\"+item.materno+\"</td>\"+\"<td>\"+item.sexo+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t \"<td>\"+item.hijos+\"</td>\"+\"<td>\"+item.sueldo+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t \"<td>\"+botonEditar+\"</td><td>\"+botonEliminar+\"</td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tnew DataTable('#TableDocente');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//asignar evento click a todos los botones con nombre de clase btn-editar\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-editar\",function(){\r\n");
      out.write("\t\t\tvar cod;\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\t$.get(\"ServletFindDocenteJSON?codigo=\"+cod, function(response){\r\n");
      out.write("\t\t\t\t//console.log(response);\r\n");
      out.write("\t\t\t\t//mostrar valores en las cajas\r\n");
      out.write("\t\t\t\t$(\"#id-codigo\").val(response.codigo);\r\n");
      out.write("\t\t\t\t$(\"#id-nombre\").val(response.nombre);\r\n");
      out.write("\t\t\t\t$(\"#id-paterno\").val(response.paterno);\r\n");
      out.write("\t\t\t\t$(\"#id-materno\").val(response.materno);\r\n");
      out.write("\t\t\t\t$(\"#id-hijos\").val(response.hijos);\r\n");
      out.write("\t\t\t\t$(\"#id-sueldo\").val(response.sueldo);\r\n");
      out.write("\t\t\t\t$(\"#id-sexo\").val(response.sexo);\r\n");
      out.write("\t\t\t\t$(\"#id-colegio\").val(response.codigoColegio);\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t//asignar evento click a todos los botones con nombre de clase btn-eliminar\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-eliminar\",function(){\r\n");
      out.write("\t\t\tvar cod;\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t  title: 'Seguro de eliminar?',\r\n");
      out.write("\t\t\t\t  text: \"Docente con ID: \"+cod,\r\n");
      out.write("\t\t\t\t  icon: 'warning',\r\n");
      out.write("\t\t\t\t  showCancelButton: true,\r\n");
      out.write("\t\t\t\t  confirmButtonColor: '#3085d6',\r\n");
      out.write("\t\t\t\t  cancelButtonColor: '#d33',\r\n");
      out.write("\t\t\t\t  confirmButtonText: 'Aceptar',\r\n");
      out.write("\t\t\t\t  cancelButtonText: 'Cancelar'\r\n");
      out.write("\t\t\t\t}).then((result) => {\r\n");
      out.write("\t\t\t\t  if (result.isConfirmed) {\r\n");
      out.write("\t\t\t\t    window.location=\"http://localhost:8080/DWI-Semana06/ServletDocente?accion=eliminar&codigo=\"+cod;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t})\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//asignar evento click al botón con ID \"btn-cerrar\"\r\n");
      out.write("\t\t$(document).on(\"click\",\"#btn-cerrar\",function(){\r\n");
      out.write("\t\t\t//resetear formulario\r\n");
      out.write("\t\t\t$(\"#formDocente\").trigger(\"reset\");\r\n");
      out.write("\t\t\t//resetar validación\r\n");
      out.write("\t\t\t$(\"#formDocente\").data(\"bootstrapValidator\").resetForm(true);\r\n");
      out.write("\t\t\t//\r\n");
      out.write("\t\t\t$(\"#id-codigo\").val(\"0\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<script>    \r\n");
      out.write("    $(document).ready(function(){     \r\n");
      out.write("        $('#formDocente').bootstrapValidator({      \r\n");
      out.write("        \t fields:{\r\n");
      out.write("        \t\t \tnombre:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo nombre es obligatorio'\r\n");
      out.write("        \t\t \t\t\t},\r\n");
      out.write("        \t\t \t\t\tregexp:{\r\n");
      out.write("        \t\t \t\t\t\tregexp:/^[a-zA-Z\\s\\ñ\\Ñ\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú\\.]{2,20}$/,\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo nombre valores errores(Letras,espacio, vocales con tilde y .)'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t},\r\n");
      out.write("        \t\t \tpaterno:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo paterno es obligatorio'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t},\r\n");
      out.write("        \t\t \tmaterno:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo materno es obligatorio'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t},\r\n");
      out.write("        \t\t \tsexo:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Seleccione sexo'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t},\r\n");
      out.write("        \t\t \tsueldo:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo sueldo es obligatorio'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t},\r\n");
      out.write("        \t\t \thijos:{\r\n");
      out.write("        \t\t \t\tvalidators:{\r\n");
      out.write("        \t\t \t\t\tnotEmpty:{\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo hijos es obligatorio'\r\n");
      out.write("        \t\t \t\t\t},\r\n");
      out.write("        \t\t \t\t\tbetween:{\r\n");
      out.write("        \t\t \t\t\t\tmin:0,\r\n");
      out.write("        \t\t \t\t\t\tmax:10,\r\n");
      out.write("        \t\t \t\t\t\tmessage:'Campo hijos solo números rango 0 - 10'\r\n");
      out.write("        \t\t \t\t\t}\r\n");
      out.write("        \t\t \t\t\t\r\n");
      out.write("        \t\t \t\t}\r\n");
      out.write("        \t\t \t}\r\n");
      out.write("        \t\t \r\n");
      out.write("        \t }\r\n");
      out.write("        });   \r\n");
      out.write("\t\t\t\r\n");
      out.write("    });    \r\n");
      out.write("</script>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /docente.jsp(134,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.docentes}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /docente.jsp(134,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t            <tr>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.paterno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.materno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sexo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.hijos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.sueldo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t                <td><button type=\"button\" class=\"btn btn-success btn-editar\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Editar</button></td>\r\n");
            out.write("\t                <td><button type=\"button\" class=\"btn btn-danger btn-eliminar\">Eliminar</button></td>\r\n");
            out.write("\t            </tr>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /docente.jsp(175,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<script>\r\n");
          out.write("\t\t\ttoastr.success(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\", toastr.options = {\r\n");
          out.write("\t\t\t\t\t\"timeOut\": \"2000\",\r\n");
          out.write("\t\t\t\t\t\"positionClass \" : \" toast-top-right \",\r\n");
          out.write("\t\t\t\t});\r\n");
          out.write("\t</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /docente.jsp(184,0) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("MENSAJE");
      // /docente.jsp(184,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
