/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2024-05-24 21:07:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class requerimiento_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Bootstrap demo</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody{\r\n");
      out.write("\t\t\tfont-family:verdana;\r\n");
      out.write("\t\t\tfont-size:12px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t.modal-header, h4, .close {\r\n");
      out.write("\t\tbackground-color: #286090;\r\n");
      out.write("\t\tcolor: white !important;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.form-control,.form-select {\r\n");
      out.write("\theight:30px!important;\r\n");
      out.write("\tfont-size:12px;\r\n");
      out.write("\t  /*padding-left: 40px!important;*/\r\n");
      out.write("\t}\r\n");
      out.write("\tfieldset, legend {\r\n");
      out.write("   all: revert;\r\n");
      out.write("}\r\n");
      out.write(".reset {\r\n");
      out.write("    all: revert;\r\n");
      out.write("}\r\n");
      out.write(".btn-danger{\r\n");
      out.write("\tmargin:0px!important;\r\n");
      out.write("\theight:30px!important;\r\n");
      out.write("\tpadding-top:3px!important;\t\r\n");
      out.write("}\r\n");
      out.write(".btn-info{\r\n");
      out.write("\tmargin:0px!important;\r\n");
      out.write("\theight:30px!important;\r\n");
      out.write("\tpadding-top:3px!important;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".colorBloqueado{\r\n");
      out.write("\tbackground:#F7EEC5;\t\r\n");
      out.write("}\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("background:#F7EEC5;\t\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script src=\"https://kit.fontawesome.com/1da5200486.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.12.1/css/all.css\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h3 class=\"text-center mt-4\">LISTA DE REQUERIMIENTOS</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <!-- Button trigger modal -->\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRequerimiento\">\r\n");
      out.write("\t\t  Nuevo Requerimiento\r\n");
      out.write("\t\t</button>\t\t\r\n");
      out.write("\t\t<div class=\" mt-2\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped table-bordered mt-5\" id=\"tableBoletas\">\r\n");
      out.write("\t\t\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t                <th>Numero</th>\r\n");
      out.write("\t\t\t\t\t                <th>Empleado</th>\r\n");
      out.write("\t\t\t\t\t                <th>Fecha</th>\r\n");
      out.write("\t\t\t\t\t                <th>Estado</th>\r\n");
      out.write("\t\t\t\t\t                <th></th>\r\n");
      out.write("\t\t\t\t\t                <th></th>\r\n");
      out.write("\t\t\t\t\t            </tr>\r\n");
      out.write("\t\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t\t  <tbody>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td><a class=\"btn btn-info btn-editar\"  data-bs-toggle=\"modal\" data-bs-target=\"#modalRequerimiento\"><i class=\"far fa-edit\"></i></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t      <td><a class=\"btn btn-danger btn-reporte\"><i class=\"far fa-trash-alt\"></i></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr> \r\n");
      out.write("\t\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"modalRequerimiento\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Requerimiento</h1>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\"><b>Numero</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control colorBloqueado\" name=\"numero\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\"><b>Empleado</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control colorBloqueado\" name=\"empleado\" id=\"id-empleado\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\"><b>Cargo</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control colorBloqueado\" name=\"cargo\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"form-group has-feedback col-3\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\" class=\"col-form-label\"><b>Estado</b></label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-select\" aria-label=\"Default select example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option selected>[Seleccione Estado]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"Nuevo\">Nuevo</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"Proceso\">Proceso</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <option value=\"Cerrado\">Cerrado</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\"><b>Fecha</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" name=\"fecha\">\r\n");
      out.write("\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group has-feedback col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\"><b>Nombre Requerimiento(Detalle)</b></label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"idDescripcion\" rows=\"10\"  name=\"descripcion\" style=\"height:90px!important\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t   placeholder=\"Ingresar detalle\" style=\"padding-left: 5px!important;\"></textarea>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<fieldset class=\"reset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <legend class=\"reset\">Consulta Bienes</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"inputEmail3\" class=\"col-sm-2\">Tipo Bien</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <select class=\"form-select\" id=\"idTipoBien\" name=\"bien\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t      <option value=\" \">[Seleccione Bien]</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button id=\"btn-consultar-tipo\" type=\"button\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"inputEmail3\" class=\"col-sm-2\">Cantidad</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t  <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t   placeholder=\"Ingresar Cantidad\" id=\"idCantidad\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button id=\"btn-consultar-tipo\" type=\"button\" class=\"btn btn-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"tableBienes\" class=\"table table-striped mt-4\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Codigo</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Descripcion</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-warning btn-adicionar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa-solid fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</fieldset>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<fieldset class=\"reset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <legend class=\"reset\">Bienes/Solicitados</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table id=\"tableSolicitados\" class=\"table table-striped mt-4\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Codigo</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Descripcion</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Cantidad</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger btn-eliminar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-trash-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</fieldset>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\"><i class=\"fas fa-save\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\"><i class=\"fa-regular fa-folder-closed\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t \t\t\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlet msg;\r\n");
      out.write("\t\tmsg=\"\";\r\n");
      out.write("\t\ttoastr.success(msg, toastr.options = {\r\n");
      out.write("\t\t\t\"timeOut\": \"2000\",\r\n");
      out.write("\t\t\t\"positionClass \" : \" toast-top-right \",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\tcargarTipoBien();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#tableBienes').dataTable( {\r\n");
      out.write("\t\t\t\t  \"searching\": false,\r\n");
      out.write("\t\t\t\t  \"lengthChange\": false,\r\n");
      out.write("\t\t\t\t  responsive: true,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#tableSolicitados').dataTable( {\r\n");
      out.write("\t\t\t\t  \"searching\": false,\r\n");
      out.write("\t\t\t\t  \"lengthChange\": false,\r\n");
      out.write("\t\t\t\t  responsive: true,\t\t  \r\n");
      out.write("\t\t} );\r\n");
      out.write("\t\t\t\t//boton buscar\r\n");
      out.write("\t\t$(document).on(\"click\",\"#btn-consultar-tipo\",function(){\r\n");
      out.write("\t\t\tlet codtipo;\r\n");
      out.write("\t\t\tcodTipo=$(\"#idTipoBien\").val();\r\n");
      out.write("\t\t\tlet botonEliminar=\"<button type='button' class='btn btn-warning btn-adicionar'><i class='fa-solid fa-plus'></i></button>\";\r\n");
      out.write("\t\t\t//DEjar en blanco la tabla\r\n");
      out.write("\t\t\t$(\"#tableBienes tbody\").empty();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.get(\"ServletBienJSON?codigoTipo=\"+codTipo,function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t//llenar tabla\r\n");
      out.write("\t\t\t\t\t$(\"#tableBienes\").append(\"<tr><td>\"+item.codigo+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t \"<td>\"+item.descripcion+\r\n");
      out.write("\t\t\t\t\t\t \"</td>\"+\"<td>\"+botonEliminar+\"</td></tr>\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t//agregar al otro lado\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-adicionar\",function(){\r\n");
      out.write("\t\t\tlet cod,des;\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tdes=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\t\t$.get(\"\"+cod,function(response){\r\n");
      out.write("\t\t\t\t$each(response,function(index,item){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-eliminar\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//JSON RECORRES\r\n");
      out.write("\t\tfunction cargarTipoBien(){\r\n");
      out.write("\t\t\t$.get(\"ServletTipoBienJSON\",function(response){\t\r\n");
      out.write("\t\t\t\t//bucle each \"for\"\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t//llenar combo\r\n");
      out.write("\t\t\t\t\t$(\"#idTipoBien\").append(\"<option value='\"+item.codigo+\"'>\"+item.descripcion+\"</option>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
